//
//  ModuleSeedPayload.swift
//  TrailTriagePro
//
//  Generated by parse_modules.py
//

import Foundation

struct ModuleSeedPayload {
    static let data: Data = {
        let rawJSON = #"""
{
  "modules": [
    {
      "moduleTitle": "About Black Elk Mountain Medicine",
      "moduleSubtitle": "================================================================================",
      "category": "General",
      "iconName": "info.circle",
      "description": "",
      "orderIndex": 0,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Teaching Philosophy",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Black Elk Mountain Medicine was started with the premise that wilderness medicine instruction should not be limited to classroom lectures. We are driven to develop a creative, experiential based curriculum; one which effectively addresses the dynamic nature of a wilderness environment and the rapid advancement in emergency care, as well as supports and addresses multiple learning styles.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Our teaching approach heavily favors hands-on, scenario-based practice taught in an outdoor setting while simulating real-world examples. The completion of scenarios plays a powerful role in self-reflection and allows for inquiry-based learning so each student can relate his or her experience to the real world.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "We believe that practice and repetition of increasingly complex scenarios helps students develop an in-depth and personalized approach to patient assessment where the learning is ingrained and can be accessed and applied rapidly in an emergency situation.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Introduction to Wilderness Medicine",
      "moduleSubtitle": "================================================================================",
      "category": "General",
      "iconName": "book.fill",
      "description": "Course Types, EMS System, and Legal Considerations",
      "orderIndex": 1,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Course Types, EMS System, and Legal Considerations\nLocation: None",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "What is Wilderness Medicine?",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Wilderness medicine is a specialized branch addressing medical and trauma emergencies in remote areas, often more complex than urban medicine. Outdoor guides, instructors, enthusiasts, and professionals working in remote backcountry locations require specialized medical training beyond traditional first aid.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Unlike urban EMS which has official governing bodies, wilderness medicine currently lacks such a body. Course curricula have historically evolved based on evidence and practical experience, leading to a de facto consensus among training organizations.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Types of Wilderness Medicine Courses",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "Wilderness First Aid (WFA) - 16 hours",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "This training is for outdoor leaders that are never far from the umbrella of the local EMS response. They are taught to recognize, treat, and stabilize basic injuries and medical issues and call for an evacuation.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Wilderness Advanced First Aid (WAFA) - 40 hours",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "The WAFA is for outdoor leaders working in remote backcountry locations that have sound communication and rescue responses. These leaders may not need to rely on their personal decision-making and/or judgment skills in the event of life and death medical decisions.",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Wilderness First Responder (WFR) - 80 hours",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "The WFR is the standard in the outdoor recreation industry for multi-day trips in remote locations with unreliable communication and where rescue is delayed or unavailable. This course is designed to address injuries, medical illnesses, and behavioral issues common to extended backcountry trips. These leaders are trained to make life and death decisions about patient treatment and to organize and manage their own rescue.",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Wilderness EMT Upgrade - 54 hours",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "This course is designed to add a wilderness module to a current Emergency Medical Technician's urban training. It focuses on the same principles of a WFR with the addition of oxygen, advanced airway techniques, intravenous therapy, and drugs. This module upgrades an urban EMT to a WEMT.",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Expedition Medicine - 45 hours",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "This course is for licensed medical practitioners (e.g. MD, PA, RN, DNP or DO) who aspire to become primary medical personnel on wilderness expeditions. This entirely field-based course covers the latest advanced care life support (ACLS) protocols applied in the field, expedition medications, first aid kits, and innovative treatment and management of common backcountry trauma, illnesses, and rescues.",
              "orderIndex": 9,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Patient Assessment",
      "moduleSubtitle": "================================================================================",
      "category": "Assessment",
      "iconName": "stethoscope",
      "description": "Scene Size-Up, Primary Assessment, Secondary Assessment, and Reassessment",
      "orderIndex": 2,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Scene Size-Up, Primary Assessment, Secondary Assessment, and Reassessment\nLocation: Yosemite National Park, California",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Patient Assessment Overview",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Four-Step Assessment Process",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Patient assessment is an organized process for gathering information about a patient, consisting of four components: 1) Scene Size-Up, 2) Primary Assessment, 3) Secondary Assessment, and 4) Reassessment. This model is standard in pre-hospital care.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Scene Size-Up",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Scene Safety\nStandard Precautions\nMechanism of Injury (MOI) / Nature of Illness (NOI)\nNumber of Patients\nResources Needed",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Primary Assessment (ABCDEG)",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "A - AIRWAY: Clear and Open Airway (Jaw Thrust or Head-Tilt, Chin-lift), Advanced Airway (OPA-NPA-King)\nB - BREATHING: Positive Pressure Ventilation (PPV), Occlusive Dressing, Stabilize Flail Chest\nC - CIRCULATION: Control Blood Loss, Check Pulses (Carotid & Radial), Perfusion (Treat for Shock)\nD - DISABILITY: Spine Precautions, AVPU\nE - EXPOSE & ENVIRONMENT: Remove/cut Clothing to Reveal Injuries, Cover Patient Up\nG - GLUCOSE: Give Sugar Orally (If unresponsive, give when patient is laying on their side)",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "warning",
              "content": "Note: Any person in a remote backcountry setting that is found unresponsive for unknown reasons should be given sugar between their cheek and gum (while lying on their side to protect their airway).",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Standard Precautions",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "Standard precautions are part of Scene Size-up and are designed to protect rescuers and patients from blood-borne pathogens, viruses, and bacteria through contact and droplet transmission.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Personal Protective Equipment (PPE)",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Gloves: Required for contact with mucous membranes, non-intact skin, blood, or other body fluids. Use non-latex gloves due to latex sensitivity. Improvise with plastic zip-lock bags if gloves are unavailable.\nProtective Surgical Masks: Required for rescuers and patients when a pathogen is transmittable via droplets.\nCPR Mask (pocket mask): Required during CPR or rescue breathing to protect rescuers from body fluids.\nEye Protection: Glasses or sunglasses help protect against disease transmission from body fluids splashing into the rescuer's eyes via droplet transmission.\nClothing: Protective clothing (e.g., rain jacket, rain pants) for significant blood splashes or major bleeding to avoid rescuer contamination.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Secondary Assessment",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Baseline Vitals, History, and Physical Exam",
          "subtitle": null,
          "orderIndex": 3,
          "content": [
            {
              "type": "paragraph",
              "content": "Baseline Vitals",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Heart Rate (HR): HR = # of beats in 15 sec. x 4 (Normal: 60-100 beats/min). Assess pulse strength: strong, weak, thready, slow, or irregular.\nRespiration Rate (RR): RR = # of chest rises in 15 sec. x 4 (Normal: 12-20 breaths/min). Listen for abnormal breath sounds (wheezing, rales, stridor), coughing, or labored breathing.\nBlood Pressure (BP): Assess strength of radial pulse. Strong \u2248 100 mmHg, Weak \u2248 80 mmHg, None = < 80 mmHg.\nLevel of Responsiveness (AVPU): Using AVPU scale - Alert and Oriented (A&O) to person, place, time, and event; Verbal stimuli; Pain Stimuli; Unresponsive.\nPupils Equal Round Reactive to Light (PERRL): Assess pupil size, equality, and reactivity.\nSkin Color \u2022 Temperature \u2022 Moisture (SCTM): Assess color (pink, red, pale, blue, yellow), temperature (warm, hot, cold), and moisture (sweating, dry, diaphoretic).\nCirculation \u2022 Sensory \u2022 Motor (CSM): Assess distal pulses and capillary refill, sensation, and motor function on all four extremities.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "History Taking (OPQRST)",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "S - Signs & Symptoms (S/Sx)\nA - Allergies\nM - Medications\nP - Pre-Existing Conditions\nL - Last Ins & Outs\nE - Events Prior",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "OPQRST (For Pain Assessment)",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "O - Onset\nP - Provoke\nQ - Quality\nR - Radiate\nS - Severity\nT - Time/Treatments",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "1ST STEP (For Altered AVPU)",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "S - Sugar\nT - Temperature\nS - Salt\nT - Toxins\nE - Electricity/Elevation\nP - Pressure",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Reassessment",
          "subtitle": null,
          "orderIndex": 4,
          "content": [
            {
              "type": "paragraph",
              "content": "Reevaluate:",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Chief Complaint\nPrimary Assessment\nVitals\nInterventions",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Document:",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "RECORD On Athletic Tape\nWRITE OUT SOAPNote\nTRANSFER TO Incident Report Form",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Basic Life Support",
      "moduleSubtitle": "================================================================================",
      "category": "Medical",
      "iconName": "heart.fill",
      "description": "CPR, Airway Management, and AED",
      "orderIndex": 3,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "CPR, Airway Management, and AED\nLocation: Rocky Mountain National Park, Colorado",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Cardiopulmonary Resuscitation (CPR)",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "CPR consists of pushing on the chest (compressions) and providing positive pressure ventilations (breaths) to circulate oxygenated blood to all vital organs, including the brain.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "When to Start CPR",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "When there are no signs of life. In addition to a palpable pulse, signs of life include chest rise, movement of any kind, and good skin color (pink skin or mucous membranes). If you witness a collapse and notice unresponsiveness, and you're in an urban setting, activate the EMS system (call 911) and use an AED, if available, before beginning compressions.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "warning",
              "content": "When there is a suspicion of asphyxia (e.g., avalanche burial, drowning, or CO & CO2 poisoning) give 5 breaths to oxygenate the patient before rescue breathing and/or CPR.",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "CPR Overview - C-A-B vs A-B-C",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "NO PULSE: Use C-A-B sequence (Circulation, Airway, Breathing)",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Circulation: Start compressions, fast and hard, allow for total chest recoil, rate of 100-120/minute\nAirway: Open airway using Head-tilt-chin-lift or Jaw thrust\nBreathing: Give two breaths, give effective breaths to make chest rise, avoid excessive ventilations, minimize interruptions to less than 10 seconds",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "PULSE PRESENT: Use A-B-C sequence (Airway, Breathing, Circulation)",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Airway: Open Airway using Head-tilt, chin-lift or Jaw thrust\nBreathing: NO Breathing or INADEQUATE Breathing (<8/min or > 30/min and shallow) = RESCUE BREATHING. Give 1 breath every 6 seconds, give effective breaths to make chest rise, avoid excessive ventilations. Continue primary assessment.",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Shock",
      "moduleSubtitle": "================================================================================",
      "category": "Medical",
      "iconName": "bolt.heart.fill",
      "description": "Types, Stages, Recognition, and Treatment",
      "orderIndex": 4,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Types, Stages, Recognition, and Treatment\nLocation: Grand Teton National Park, Wyoming",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Types of Shock",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Normal",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Fluid level, pump & container are normal. HR: 60-100 bpm, RR: 12-24 bpm, BP: Normal (strong radial pulses), SCTM: Pink, warm & dry (PWD).",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Hypovolemic Shock",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Fluid problem, severe bleed or severe dehydration. Visual: Healthy red heart connected to red circular container, but blue liquid level significantly reduced (<4 liters). HR: Over 100 bpm, RR: Over 24 bpm, BP: Normal to low, SCTM: Pale, cool & clammy (PCC).",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Cardiogenic Shock",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Pump problem: MI, CHF or cardiac tamponade. Visual: Red heart with diagonal line through it (indicating problem), connected to red circular container completely filled with blue liquid (5 liters). HR: Over 100 bpm, RR: Over 24 bpm, BP: Normal to low, SCTM: Pale, cool & clammy (PCC). Diaphoresis (sweating profusely) is common.",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Anaphylactic Shock (Vasogenic)",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Container problem, severe allergy. HR: Over 100 bpm, RR: Over 24 bpm (wheezing), BP: Low, SCTM: Red, hot & sweaty (RHS). Swallowing and breathing difficulties are common. Abdominal pain, cramps, vomiting, diarrhea, hives, and angioedema (swelling similar to hives, but beneath the skin instead of on the surface) is also possible.",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Septic Shock (Vasogenic)",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Container problem, severe infection. HR: Over 100 bpm, RR: Over 24 bpm, BP: Low, SCTM: Red & hot. A fever is usually present.",
              "orderIndex": 9,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Neurogenic Shock (Vasogenic)",
              "orderIndex": 10,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Container problem, high cord injury (C1-T4). HR: Over 100 bpm (or below 60/min bradycardia in some cases depending on spinal cord injury), RR: Over 24 bpm or absent, BP: Low, SCTM: Red, hot & dry (RHD), CSM: Poor (especially sensory and motor). Neck and/or back pain is usually present if patient is conscious.",
              "orderIndex": 11,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Stages of Shock",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "Compensatory Shock",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Signs/Symptoms:",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Approximately 1 liter of blood loss\nAVPU: Anxious, restless, & confused\nSCTM: Pale, cool, clammy, & diaphoretic\nHR: Tachycardia (above 100 bpm)\nRR: Tachypnea (above 24 bpm)\nBP: Strong radial pulse\nPERRL: Normal",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Decompensatory Shock",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Signs/Symptoms:",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Approximately 2 liters of blood loss\nAVPU: Drops to unresponsiveness\nSCTM: Very pale, cool, & clammy\nHR: Increased tachycardia (weak & thready)\nRR: Increased tachypnea (rapid & shallow)\nBP: No radial pulse bilaterally\nPERRL: Pupils are slow to react",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Irreversible Shock",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Signs/Symptoms:",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Over 2 liters of blood loss\nAVPU: Unresponsive\nSCTM: Cold & mottled\nHR: Extreme tachycardia (weak & thready)\nRR: Extreme tachypnea (rapid & shallow)\nBP: Weak to no palpable carotid pulses\nPERRL: Fixed & dilated",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Treatment",
          "subtitle": null,
          "orderIndex": 3,
          "content": [
            {
              "type": "paragraph",
              "content": "Tx (Treatment):",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Assess ABCs\nStop blood loss\nAnticipate shock\nKeep patient calm & warm\nIV therapy if available\nHigh flow O\u2082 if available\nEvacuate immediately",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "warning",
              "content": "NOTE: Individuals who take beta-blockers or calcium channel blockers for high BP or arrhythmias may decompensate more rapidly with shock since these drugs block the heart from beating above 100 bpm. Beta-blockers end in \"olol\" (e.g., metoprolol, atenolol & propranolol). Calcium channel blockers end in \"dipine\" (e.g., amlodipine, nicardipine & felodipine).",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Cardiac Emergencies",
      "moduleSubtitle": "================================================================================",
      "category": "Medical",
      "iconName": "heart.text.square.fill",
      "description": "Angina, MI, CHF, and Treatment Protocols",
      "orderIndex": 5,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Angina, MI, CHF, and Treatment Protocols\nLocation: Glacier National Park, Montana",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Angina Pectoris",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Signs/Symptoms (S/Sx)",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Anxiety & denial\nChest pain/pressure\nPain that radiates to the left jaw and arm\nShortness of breath (SOB)\nWeakness\nPale skin\nDiaphoresis (sweating profusely)\nPossible elevated HR and RR\nS/Sx often resolves with rest and/or nitroglycerin",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "note",
              "content": "Some individuals may simply present with weakness, nausea and/or pain in the back and/or belly.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Myocardial Infarction (MI)",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "Signs/Symptoms (S/Sx)",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Anxiety & denial\nNausea & vomiting\nChest pain/pressure\nPain that radiates to the left jaw and arm\nShortness of breath (SOB)\nWeakness\nPale cool & clammy\nDiaphoresis (sweating profusely)\nElevated HR & RR\nCardiogenic shock especially if on betablockers and CCBs",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "note",
              "content": "Some individuals may simply present with weakness, nausea and/or pain in the back and/or belly.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Congestive Heart Failure (CHF)",
          "subtitle": null,
          "orderIndex": 3,
          "content": [
            {
              "type": "paragraph",
              "content": "Signs/Symptoms (S/Sx)",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Weakness & fatigue\nNausea & vomiting\nSwollen ankles and legs or shortness of breath due to pulmonary edema (crackly lung sounds)\nMay have chest pain\nIncreased HR & RR",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Treatment (Tx)",
          "subtitle": null,
          "orderIndex": 4,
          "content": [
            {
              "type": "procedure",
              "content": "General Treatment:",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Rest\nPosition of comfort\n325 mg of Aspirin\nPatient's Rx of nitroglycerin\nCPR when indicated\nEvacuate immediately!",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Stroke (CVA)",
      "moduleSubtitle": "================================================================================",
      "category": "Medical",
      "iconName": "brain.head.profile",
      "description": "Recognition, FAST Assessment, and Treatment",
      "orderIndex": 6,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Recognition, FAST Assessment, and Treatment\nLocation: Mount Rainier National Park, Washington",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "What is a Stroke (CVA)?",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "A CVA (stroke) occurs when either a blood clot lodges in a cerebral blood vessel (ischemic stroke) or a cerebral artery ruptures (hemorrhagic stroke), both leading to inadequate tissue perfusion of the brain.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Neurological damage from an ischemic stroke might be reversible with thrombolytics, which dissolve clots to improve blood flow and prevent permanent brain damage. This therapy is for certain patients and must be administered within a 4.5-hour window after symptom onset.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "A stroke has sudden onset. It is critical to determine a \"Last Seen Normal\" time from the patient or bystanders. Proper wilderness treatment involves accurate assessment, patient comfort, and prompt evacuation.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Aphasia",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Aphasia is an impairment of language, common in strokes and other brain injuries. It can present in three ways: 1) inability to form words and speak while understanding others, 2) inability to comprehend language resulting in incomprehensible speech, or 3) a combination of both. Individuals who can comprehend language might still communicate in written form.",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Signs and Symptoms",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "bulletList",
              "content": "Headache\nSlurred speech\nHemiparesis (one-sided weakness)\nHemiplegia (paralysis on one side of the body)\nLoss of CSM on one side (Circulation, Sensation, Movement)\nAphasia\nDifficulty breathing\nDecreased AVPU (Level of Responsiveness)",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "FAST Assessment",
          "subtitle": null,
          "orderIndex": 3,
          "content": [
            {
              "type": "paragraph",
              "content": "F - Facial Droop",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Partial paralysis of one side of the face results in drooping features. Instruction: Ask the person to smile.",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "A - Arm Drift",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "The person cannot raise or hold arms up equally. Instruction: Ask the person to hold both arms straight out in front of them with palms up.",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "S - Speech",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "The person slurs words, uses the wrong words or is unable to speak. There may also be difficulty swallowing exhibited by coughing or choking. Instruction: Ask the person to repeat a sentence after you.",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "T - Time",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Time lost is brain lost. Think 'Brain Attack', like 'Heart Attack'. Instructions: Ask family/friends/bystanders when the person was last seen acting normally. Evacuate immediately!!",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Treatment",
          "subtitle": null,
          "orderIndex": 4,
          "content": [
            {
              "type": "paragraph",
              "content": "Tx (Treatment):",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "ABCs (Airway, Breathing, Circulation)\nAssess & document \"FAST\" (Face drooping, Arm weakness, Speech difficulty, Time to call emergency services)\nReassurance\nEvacuate immediately!",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "warning",
              "content": "NEVER give aspirin in the event of a CVA. It will increase bleeding in the brain in the case of a hemorrhagic stroke.",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Hypothermia",
      "moduleSubtitle": "================================================================================",
      "category": "Environmental",
      "iconName": "thermometer.snowflake",
      "description": "Stages, Recognition, and Treatment",
      "orderIndex": 7,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Stages, Recognition, and Treatment\nLocation: Denali National Park, Alaska",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Assessing Hypothermia",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Assessment Steps:",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "numberedList",
              "content": "1. Assess Consciousness (conscious or unresponsive)\n2. Assess Movement (normal, impaired, or no movement)\n3. Assess Shivering (mild, uncontrollable, or decreasing)\n4. Assess AVPU (A&Ox4, decreasing, \"U\" on AVPU)",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Stages of Hypothermia",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "COLD STRESSED",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Indicators:",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "CONSCIOUS\nMOVEMENT NORMAL\nSHIVERING\nAVPU = A&Ox4 (Level of Responsiveness = Alert & Oriented x4)",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment:\n1. Reduce heat loss\n2. Provide high-calorie food or drink\n3. Move around/exercise to warm up",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "MILD",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Indicators:",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "CONSCIOUS\nIMPAIRED MOVEMENT\nSHIVERING\nAVPU = A&Ox4",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment:\n1. Handle gently\n2. Have patient sit or lie down in hypowrap for at least 30 min.\n3. Heat sources - chest, back, armpits\n4. Give high-calorie food/drink\n5. Monitor for 'afterdrop' if patient recovers\n6. Evacuate if no improvement",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "MODERATE",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Indicators:",
              "orderIndex": 9,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "CONSCIOUS\nUNCONTROLLABLE SHIVERING \u2192 NONE\n\u2193AVPU (decreasing Level of Responsiveness)",
              "orderIndex": 10,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment:\n1. No standing/walking\n2. Handle gently\n3. Keep horizontal in hypowrap\n4. Heat sources - chest, back, armpits\n5. No food or drink\n6. Evacuate carefully to hospital with ECLS capability",
              "orderIndex": 11,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "SEVERE",
              "orderIndex": 12,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "If cold & unresponsive, assume SEVERE HYPOTHERMIA",
              "orderIndex": 13,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment:\n1. Check carotid pulse for 60 sec.",
              "orderIndex": 14,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "IF no pulse, start CPR\nIF pulse but no breathing, rescue breathe: (1 breath every 5-6 sec.)",
              "orderIndex": 15,
              "metadata": null,
              "location": null
            },
            {
              "type": "numberedList",
              "content": "2. Treat like Moderate Hypothermia\n3. Evacuate carefully ASAP to hospital with ECLS capability",
              "orderIndex": 16,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    },
    {
      "moduleTitle": "Skin Related Problems",
      "moduleSubtitle": "================================================================================",
      "category": "Minor Issues",
      "iconName": "hand.raised.fill",
      "description": "Poison Ivy, Oak, Sumac, and Fungal Infections",
      "orderIndex": 8,
      "location": null,
      "sections": [
        {
          "sectionTitle": "Introduction",
          "subtitle": null,
          "orderIndex": 0,
          "content": [
            {
              "type": "paragraph",
              "content": "Poison Ivy, Oak, Sumac, and Fungal Infections\nLocation: Great Smoky Mountains National Park, North Carolina/Tennessee",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Poison Ivy, Oak & Sumac",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Toxicodendron Genus",
          "subtitle": null,
          "orderIndex": 1,
          "content": [
            {
              "type": "paragraph",
              "content": "Contact dermatitis caused by plants in the Toxicodendron genus. Urushiol-induced contact dermatitis can be severe (potential for anaphylaxis). Approximately 15-30% of people are non-allergic. Risk of inhaling fumes from burning plants. Toxicodendron sp. is found across the US and southern Canada, excluding deserts and altitudes above ~5000 ft (1524 m).",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Prevention",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Recognize plants by \"leaves of three\"\nWear protective clothing\nWash exposed clothing with laundry detergent or special solvents like Tecnu\u00ae products",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Signs/Symptoms (S/Sx)",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Extremely itchy, red rash containing small to large fluid-filled blisters\nOutbreaks can last up to three weeks\nDifficulty breathing from inhalation of fumes from burning the plant",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment (Tx)",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "numberedList",
              "content": "1. Wash exposed area immediately with soap and cold water (avoiding hot water to prevent pore opening and faster absorption)\n2. Use Tecnu Extreme\u00ae for its oil-dissolving and anti-itch properties\n3. Consider anti-histamines or oral steroids for severe reactions",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "warning",
              "content": "Evacuate anyone who has inhaled fumes or has difficulty breathing.",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            }
          ]
        },
        {
          "sectionTitle": "Fungal Infections",
          "subtitle": null,
          "orderIndex": 2,
          "content": [
            {
              "type": "paragraph",
              "content": "Fungal infections typically grow in dark, warm, moist areas like feet and groin.",
              "orderIndex": 0,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Prevention",
              "orderIndex": 1,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Wear breathable, dry clothing\nFrequently change socks and underwear to reduce moisture in problem areas",
              "orderIndex": 2,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "Signs/Symptoms (S/Sx)",
              "orderIndex": 3,
              "metadata": null,
              "location": null
            },
            {
              "type": "bulletList",
              "content": "Red, swollen, itchy, skin that can be scaling and cracking",
              "orderIndex": 4,
              "metadata": null,
              "location": null
            },
            {
              "type": "procedure",
              "content": "Treatment (Tx)",
              "orderIndex": 5,
              "metadata": null,
              "location": null
            },
            {
              "type": "numberedList",
              "content": "1. Clean and air-dry the affected area\n2. Allow it to breathe\n3. Short exposure to UV radiation may help\n4. Apply diluted tea tree oil, 1% hydrocortisone cream, or other over-the-counter anti-fungal creams",
              "orderIndex": 6,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "================================================================================\nEND OF MODULES\n================================================================================",
              "orderIndex": 7,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "This extraction represents a comprehensive migration from chapter-based reference material to modern, topic-based modules with rebranding to Black Elk Mountain Medicine and terminology updates (SOAA'P \u2192 SOAPNote).",
              "orderIndex": 8,
              "metadata": null,
              "location": null
            },
            {
              "type": "paragraph",
              "content": "All modules include randomized scenario locations from US National and State Parks for enhanced learning and scenario realism.",
              "orderIndex": 9,
              "metadata": null,
              "location": null
            }
          ]
        }
      ]
    }
  ]
}
"""#
        guard let data = rawJSON.data(using: .utf8) else {
            fatalError("Unable to encode seed JSON")
        }
        return data
    }()
}
